/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2_0' in SOPC Builder design 'nios_setup'
 * SOPC Builder design path: ../../nios_setup.sopcinfo
 *
 * Generated: Tue Feb 09 21:07:26 CET 2021
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00010820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x11
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00008020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x11
#define ALT_CPU_NAME "nios2_gen2_0"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00008000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00010820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x11
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00008020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x11
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00008000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_TIMER
#define __ALTERA_MODULAR_ADC
#define __ALTERA_NIOS2_GEN2


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "MAX 10"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x11250
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x11250
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x11250
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "nios_setup"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 4
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x11250
#define JTAG_UART_0_IRQ 0
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * led_io configuration
 *
 */

#define ALT_MODULE_CLASS_led_io altera_avalon_pio
#define LED_IO_BASE 0x11220
#define LED_IO_BIT_CLEARING_EDGE_REGISTER 0
#define LED_IO_BIT_MODIFYING_OUTPUT_REGISTER 1
#define LED_IO_CAPTURE 0
#define LED_IO_DATA_WIDTH 3
#define LED_IO_DO_TEST_BENCH_WIRING 0
#define LED_IO_DRIVEN_SIM_VALUE 0
#define LED_IO_EDGE_TYPE "NONE"
#define LED_IO_FREQ 50000000
#define LED_IO_HAS_IN 0
#define LED_IO_HAS_OUT 1
#define LED_IO_HAS_TRI 0
#define LED_IO_IRQ -1
#define LED_IO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LED_IO_IRQ_TYPE "NONE"
#define LED_IO_NAME "/dev/led_io"
#define LED_IO_RESET_VALUE 0
#define LED_IO_SPAN 32
#define LED_IO_TYPE "altera_avalon_pio"


/*
 * modular_adc_0_sample_store_csr configuration
 *
 */

#define ALT_MODULE_CLASS_modular_adc_0_sample_store_csr altera_modular_adc
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_BASE 0x11000
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CORE_VARIANT 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_LENGTH 64
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_0 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_1 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_10 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_11 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_12 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_13 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_14 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_15 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_16 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_17 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_18 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_19 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_2 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_20 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_21 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_22 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_23 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_24 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_25 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_26 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_27 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_28 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_29 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_3 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_30 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_31 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_32 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_33 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_34 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_35 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_36 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_37 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_38 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_39 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_4 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_40 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_41 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_42 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_43 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_44 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_45 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_46 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_47 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_48 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_49 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_5 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_50 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_51 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_52 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_53 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_54 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_55 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_56 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_57 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_58 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_59 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_6 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_60 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_61 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_62 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_63 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_7 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_8 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_9 17
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_IRQ -1
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_NAME "/dev/modular_adc_0_sample_store_csr"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_PRESCALER_CH16 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_PRESCALER_CH8 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_REFSEL "Internal VREF"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_SPAN 512
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_TYPE "altera_modular_adc"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH0 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH1 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH10 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH11 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH12 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH13 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH14 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH15 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH16 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH2 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH3 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH4 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH5 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH6 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH7 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH8 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH9 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_TSD 1
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_VREF 2.5


/*
 * modular_adc_0_sequencer_csr configuration
 *
 */

#define ALT_MODULE_CLASS_modular_adc_0_sequencer_csr altera_modular_adc
#define MODULAR_ADC_0_SEQUENCER_CSR_BASE 0x11258
#define MODULAR_ADC_0_SEQUENCER_CSR_CORE_VARIANT 0
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_LENGTH 64
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_0 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_1 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_10 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_11 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_12 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_13 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_14 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_15 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_16 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_17 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_18 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_19 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_2 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_20 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_21 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_22 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_23 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_24 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_25 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_26 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_27 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_28 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_29 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_3 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_30 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_31 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_32 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_33 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_34 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_35 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_36 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_37 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_38 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_39 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_4 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_40 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_41 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_42 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_43 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_44 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_45 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_46 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_47 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_48 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_49 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_5 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_50 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_51 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_52 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_53 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_54 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_55 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_56 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_57 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_58 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_59 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_6 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_60 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_61 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_62 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_63 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_7 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_8 17
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_9 17
#define MODULAR_ADC_0_SEQUENCER_CSR_IRQ -1
#define MODULAR_ADC_0_SEQUENCER_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MODULAR_ADC_0_SEQUENCER_CSR_NAME "/dev/modular_adc_0_sequencer_csr"
#define MODULAR_ADC_0_SEQUENCER_CSR_PRESCALER_CH16 0
#define MODULAR_ADC_0_SEQUENCER_CSR_PRESCALER_CH8 0
#define MODULAR_ADC_0_SEQUENCER_CSR_REFSEL "Internal VREF"
#define MODULAR_ADC_0_SEQUENCER_CSR_SPAN 8
#define MODULAR_ADC_0_SEQUENCER_CSR_TYPE "altera_modular_adc"
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH0 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH1 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH10 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH11 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH12 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH13 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH14 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH15 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH16 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH2 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH3 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH4 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH5 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH6 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH7 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH8 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH9 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_TSD 1
#define MODULAR_ADC_0_SEQUENCER_CSR_VREF 2.5


/*
 * onchip_memory2_0 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory2_0 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_BASE 0x8000
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE "nios_setup_onchip_memory2_0"
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY2_0_IRQ -1
#define ONCHIP_MEMORY2_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY2_0_NAME "/dev/onchip_memory2_0"
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 32768
#define ONCHIP_MEMORY2_0_SPAN 32768
#define ONCHIP_MEMORY2_0_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_0_WRITABLE 1


/*
 * one_sec_timer configuration
 *
 */

#define ALT_MODULE_CLASS_one_sec_timer altera_avalon_timer
#define ONE_SEC_TIMER_ALWAYS_RUN 0
#define ONE_SEC_TIMER_BASE 0x11200
#define ONE_SEC_TIMER_COUNTER_SIZE 32
#define ONE_SEC_TIMER_FIXED_PERIOD 0
#define ONE_SEC_TIMER_FREQ 50000000
#define ONE_SEC_TIMER_IRQ 1
#define ONE_SEC_TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define ONE_SEC_TIMER_LOAD_VALUE 49999999
#define ONE_SEC_TIMER_MULT 1.0
#define ONE_SEC_TIMER_NAME "/dev/one_sec_timer"
#define ONE_SEC_TIMER_PERIOD 1
#define ONE_SEC_TIMER_PERIOD_UNITS "s"
#define ONE_SEC_TIMER_RESET_OUTPUT 0
#define ONE_SEC_TIMER_SNAPSHOT 1
#define ONE_SEC_TIMER_SPAN 32
#define ONE_SEC_TIMER_TICKS_PER_SEC 1
#define ONE_SEC_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define ONE_SEC_TIMER_TYPE "altera_avalon_timer"


/*
 * sw_io configuration
 *
 */

#define ALT_MODULE_CLASS_sw_io altera_avalon_pio
#define SW_IO_BASE 0x11240
#define SW_IO_BIT_CLEARING_EDGE_REGISTER 0
#define SW_IO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SW_IO_CAPTURE 1
#define SW_IO_DATA_WIDTH 3
#define SW_IO_DO_TEST_BENCH_WIRING 0
#define SW_IO_DRIVEN_SIM_VALUE 0
#define SW_IO_EDGE_TYPE "RISING"
#define SW_IO_FREQ 50000000
#define SW_IO_HAS_IN 1
#define SW_IO_HAS_OUT 0
#define SW_IO_HAS_TRI 0
#define SW_IO_IRQ -1
#define SW_IO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SW_IO_IRQ_TYPE "NONE"
#define SW_IO_NAME "/dev/sw_io"
#define SW_IO_RESET_VALUE 0
#define SW_IO_SPAN 16
#define SW_IO_TYPE "altera_avalon_pio"

#endif /* __SYSTEM_H_ */
